### PR TITLE
need to redirect to /search after clicking recommend button in /library

### PR DESCRIPTION
**Pull request by tylerjhevia**
@bretthev I want to redirect to my /search path when I click my recommend button. I tried using <Redirect to='/search' but that didn't work. What do you think would be a good way to do it? Here's my current onClick function for the button: `<button
        className="recommend-button"
        onClick={() => props.recommendBook(volumeInfo)}
      >`

### CODE REVIEW

**Comment by bretthev** [comment]
So you want the recommend button to be a link and a normal button?

**Comment by bretthev** [comment]
You could write a function that does the `recommendBook(whatever)` thing and then redirects to `search`. You're using react router 4, yeah? `props.location.push('/search)` or something like that?

**Comment by tylerjhevia** [comment]
I'll try the push thing. Thanks

**Comment by tylerjhevia** [comment]
My BookCard doesn't have location in it's props, maybe because it's not an actual React Component? Redirect wasn't working so I made the button a NavLink instead.

**Comment by tylerjhevia** [comment]
Go gators

**Pull request merged**
